update base BSP to 3.0.6
File from Renesas: RTK0EF0045Z0024AZJ-v3.0.6.zip

Signed-off-by: Alexandru Ardelean <alex@shruggie.ro>

diff --git a/meta-virtualization/recipes-containers/lxc/files/templates-use-curl-instead-of-wget.patch b/meta-virtualization/recipes-containers/lxc/files/templates-use-curl-instead-of-wget.patch
--- a/meta-virtualization/recipes-containers/lxc/files/templates-use-curl-instead-of-wget.patch
+++ b/meta-virtualization/recipes-containers/lxc/files/templates-use-curl-instead-of-wget.patch
@@ -1,4 +1,4 @@
-From 07890dd8ffdcd08b7be1ddbd9f56ac55482c76bb Mon Sep 17 00:00:00 2001
+From 1db2db7783bd7ec2aa1da86e640019891634c659 Mon Sep 17 00:00:00 2001
 From: Joakim Roubert <joakimr@axis.com>
 Date: Fri, 16 Aug 2019 07:52:48 +0200
 Subject: [PATCH] Use curl instead of wget
@@ -7,16 +7,16 @@ When curl's MIT license is preferable to wget's GPLv3.
 
 Change-Id: I4684ae7569704514fdcc63e0655c556efcaf44f8
 Signed-off-by: Joakim Roubert <joakimr@axis.com>
-
+Signed-off-by: Yanfei Xu <yanfei.xu@windriver.com>
 ---
  templates/lxc-download.in | 10 +++++-----
  1 file changed, 5 insertions(+), 5 deletions(-)
 
-diff --git a/templates/lxc-download.in b/templates/lxc-download.in
-index d7e6128..8a4b567 100644
---- a/templates/lxc-download.in
-+++ b/templates/lxc-download.in
-@@ -74,9 +74,9 @@ cleanup() {
+Index: git/templates/lxc-download.in
+===================================================================
+--- git.orig/templates/lxc-download.in
++++ git/templates/lxc-download.in
+@@ -59,9 +59,9 @@
    fi
  }
  
@@ -28,18 +28,19 @@ index d7e6128..8a4b567 100644
        return 0
      fi
    done
-@@ -85,8 +85,8 @@ wget_wrapper() {
+@@ -70,8 +70,9 @@
  }
  
  download_file() {
--  if ! wget_wrapper -T 30 -q "https://${DOWNLOAD_SERVER}/$1" -O "$2" >/dev/null 2>&1; then
--    if ! wget_wrapper -T 30 -q "http://${DOWNLOAD_SERVER}/$1" -O "$2" >/dev/null 2>&1; then
-+  if ! curl_wrapper -m 30 -s "https://${DOWNLOAD_SERVER}/$1" -o "$2" >/dev/null 2>&1; then
-+    if ! curl_wrapper -m 30 -s "http://${DOWNLOAD_SERVER}/$1" -o "$2" >/dev/null 2>&1; then
-       if [ "$3" = "noexit" ]; then
-         return 1
-       else
-@@ -271,7 +271,7 @@ while :; do
+-  if ! wget_wrapper --user-agent="lxc/@PACKAGE_VERSION@ compat:${DOWNLOAD_COMPAT_LEVEL}" -T 30 -q "https://${DOWNLOAD_SERVER}/$1" -O "$2" >/dev/null 2>&1; then
+-    if [ "$3" = "noexit" ]; then
++  if ! curl_wrapper --user-agent="lxc/@PACKAGE_VERSION@ compat:${DOWNLOAD_COMPAT_LEVEL}" -m 30 -s "https://${DOWNLOAD_SERVER}/$1" -o "$2" >/dev/null 2>&1; then
++    if ! curl_wrapper --user-agent="lxc/@PACKAGE_VERSION@ compat:${DOWNLOAD_COMPAT_LEVEL}" -m 30 -s "http://${DOWNLOAD_SERVER}/$1" -o "$2" >/dev/null 2>&1; then
++      if [ "$3" = "noexit" ]; then
+       return 1
+     else
+       echo "ERROR: Failed to download https://${DOWNLOAD_SERVER}/$1" 1>&2
+@@ -176,7 +177,7 @@
  done
  
  # Check for required binaries
